version: '3.8'
services:
  dosvob:
    build:
      context: .
      target: debug
    restart: no
    volumes:
      - "dosvob:/app/backups"
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"
volumes:
  dosvob:
    name: dosvob