version: '3.8'
services:
  dosvob:
    build:
      context: .
      target: cron
    restart: always
    volumes:
      - "./backups:/app/backups"
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"
volumes:
  dosvob:
    name: dosvob